version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Tirocinio
      - MYSQL_USER=francesco
      - MYSQL_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
